# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11f7d55ddb3f83bbedb2dc8f52c7e26531ce1848e22a28562fab44a989808282e35449ae92efd6e81558862aee56bae4078080f74053b19cbb36b0404d206f0c

test:
  secret_key_base: 4a0fe1dccea66697eb3f11a2ce1de4137021a9648fd4f6db02458c10bf04f133d22deadc5cad6d4c6e068fbd1e26e1a3458c267c296fa8b90452d73ef338627f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
